import { Route, Bus, Stop, ServiceAlert, PassengerProfile } from '../context/PassengerContext';

export const mockRoutesData: Route[] = [
  {
    id: 'route1',
    name: 'Route 1: City Center - Airport',
    source: 'Kathmandu City Center',
    destination: 'Kathmandu International Airport',
    distance: 28,
    busesCount: 5,
    stops: [
      {
        id: 'stop1',
        name: 'Kathmandu City Center',
        latitude: 27.7172,
        longitude: 85.3240,
        estimatedArrival: new Date().toISOString(),
        order: 1,
      },
      {
        id: 'stop2',
        name: 'Chabahil',
        latitude: 27.7220,
        longitude: 85.3450,
        estimatedArrival: new Date(Date.now() + 15 * 60000).toISOString(),
        order: 2,
      },
      {
        id: 'stop3',
        name: 'Bhaktapur',
        latitude: 27.6721,
        longitude: 85.4295,
        estimatedArrival: new Date(Date.now() + 30 * 60000).toISOString(),
        order: 3,
      },
      {
        id: 'stop4',
        name: 'Kathmandu International Airport',
        latitude: 27.8156,
        longitude: 85.9123,
        estimatedArrival: new Date(Date.now() + 60 * 60000).toISOString(),
        order: 4,
      },
    ],
  },
  {
    id: 'route2',
    name: 'Route 2: Thamel - Boudhanath',
    source: 'Thamel',
    destination: 'Boudhanath',
    distance: 8,
    busesCount: 8,
    stops: [
      {
        id: 'stop5',
        name: 'Thamel Bus Station',
        latitude: 27.7160,
        longitude: 85.3040,
        estimatedArrival: new Date().toISOString(),
        order: 1,
      },
      {
        id: 'stop6',
        name: 'Pasupatinath Temple',
        latitude: 27.7280,
        longitude: 85.3340,
        estimatedArrival: new Date(Date.now() + 10 * 60000).toISOString(),
        order: 2,
      },
      {
        id: 'stop7',
        name: 'Boudhanath Stupa',
        latitude: 27.7212,
        longitude: 85.3577,
        estimatedArrival: new Date(Date.now() + 20 * 60000).toISOString(),
        order: 3,
      },
    ],
  },
  {
    id: 'route3',
    name: 'Route 3: Pokhara Express',
    source: 'Kathmandu',
    destination: 'Pokhara',
    distance: 200,
    busesCount: 3,
    stops: [
      {
        id: 'stop8',
        name: 'Kathmandu Main Terminal',
        latitude: 27.7180,
        longitude: 85.3200,
        estimatedArrival: new Date().toISOString(),
        order: 1,
      },
      {
        id: 'stop9',
        name: 'Prithvi Highway Midpoint',
        latitude: 27.9800,
        longitude: 85.2100,
        estimatedArrival: new Date(Date.now() + 90 * 60000).toISOString(),
        order: 2,
      },
      {
        id: 'stop10',
        name: 'Pokhara Bus Station',
        latitude: 28.2096,
        longitude: 83.9856,
        estimatedArrival: new Date(Date.now() + 180 * 60000).toISOString(),
        order: 3,
      },
    ],
  },
  {
    id: 'route4',
    name: 'Route 4: Patan - Kirtipur',
    source: 'Patan Durbar Square',
    destination: 'Kirtipur',
    distance: 12,
    busesCount: 6,
    stops: [
      {
        id: 'stop11',
        name: 'Patan Durbar Square',
        latitude: 27.6743,
        longitude: 85.3140,
        estimatedArrival: new Date().toISOString(),
        order: 1,
      },
      {
        id: 'stop12',
        name: 'Lagankhel',
        latitude: 27.6850,
        longitude: 85.3000,
        estimatedArrival: new Date(Date.now() + 15 * 60000).toISOString(),
        order: 2,
      },
      {
        id: 'stop13',
        name: 'Kirtipur',
        latitude: 27.6611,
        longitude: 85.2850,
        estimatedArrival: new Date(Date.now() + 30 * 60000).toISOString(),
        order: 3,
      },
    ],
  },
];

export const mockBusesData: Bus[] = [
  {
    id: 'bus1',
    busNumber: 'KTM-001',
    routeId: 'route1',
    driverName: 'Ram Kumar',
    currentStop: 'Chabahil',
    latitude: 27.7220,
    longitude: 85.3450,
    totalCapacity: 50,
    currentPassengers: 32,
    status: 'active',
    nextStop: 'Bhaktapur',
    estimatedNextStopTime: new Date(Date.now() + 15 * 60000).toISOString(),
    delay: 0,
  },
  {
    id: 'bus2',
    busNumber: 'KTM-002',
    routeId: 'route1',
    driverName: 'Shyam Singh',
    currentStop: 'Kathmandu City Center',
    latitude: 27.7172,
    longitude: 85.3240,
    totalCapacity: 50,
    currentPassengers: 25,
    status: 'active',
    nextStop: 'Chabahil',
    estimatedNextStopTime: new Date(Date.now() + 25 * 60000).toISOString(),
    delay: 0,
  },
  {
    id: 'bus3',
    busNumber: 'TM-001',
    routeId: 'route2',
    driverName: 'Hari Paudel',
    currentStop: 'Pasupatinath Temple',
    latitude: 27.7280,
    longitude: 85.3340,
    totalCapacity: 45,
    currentPassengers: 38,
    status: 'active',
    nextStop: 'Boudhanath Stupa',
    estimatedNextStopTime: new Date(Date.now() + 12 * 60000).toISOString(),
    delay: 2,
  },
  {
    id: 'bus4',
    busNumber: 'TM-002',
    routeId: 'route2',
    driverName: 'Deepak Sharma',
    currentStop: 'Thamel Bus Station',
    latitude: 27.7160,
    longitude: 85.3040,
    totalCapacity: 45,
    currentPassengers: 15,
    status: 'active',
    nextStop: 'Pasupatinath Temple',
    estimatedNextStopTime: new Date(Date.now() + 10 * 60000).toISOString(),
    delay: 0,
  },
  {
    id: 'bus5',
    busNumber: 'PKR-001',
    routeId: 'route3',
    driverName: 'Narendra Niraula',
    currentStop: 'Kathmandu Main Terminal',
    latitude: 27.7180,
    longitude: 85.3200,
    totalCapacity: 55,
    currentPassengers: 50,
    status: 'active',
    nextStop: 'Prithvi Highway Midpoint',
    estimatedNextStopTime: new Date(Date.now() + 90 * 60000).toISOString(),
    delay: 0,
  },
  {
    id: 'bus6',
    busNumber: 'PT-001',
    routeId: 'route4',
    driverName: 'Sita Thapa',
    currentStop: 'Lagankhel',
    latitude: 27.6850,
    longitude: 85.3000,
    totalCapacity: 40,
    currentPassengers: 20,
    status: 'active',
    nextStop: 'Kirtipur',
    estimatedNextStopTime: new Date(Date.now() + 15 * 60000).toISOString(),
    delay: 0,
  },
];

export const mockAlertsData: ServiceAlert[] = [
  {
    id: 'alert1',
    type: 'delay',
    routeId: 'route1',
    title: 'Traffic Congestion',
    message: 'Route 1 experiencing 10 minutes delay due to traffic near Chabahil',
    severity: 'warning',
    timestamp: new Date(Date.now() - 5 * 60000).toISOString(),
    read: false,
  },
  {
    id: 'alert2',
    type: 'maintenance',
    busId: 'bus3',
    title: 'Scheduled Maintenance',
    message: 'Bus TM-001 will undergo maintenance tomorrow. Alternative service available.',
    severity: 'info',
    timestamp: new Date(Date.now() - 30 * 60000).toISOString(),
    read: false,
  },
  {
    id: 'alert3',
    type: 'maintenance',
    routeId: 'route2',
    title: 'Service Update',
    message: 'Additional buses added to Route 2 during peak hours.',
    severity: 'info',
    timestamp: new Date(Date.now() - 2 * 3600000).toISOString(),
    read: true,
  },
];

export const mockProfileData: PassengerProfile = {
  id: 'passenger1',
  name: 'Rajesh Sharma',
  email: 'rajesh@example.com',
  phone: '+977 98xxxxxxxx',
  totalTrips: 45,
  totalSpent: 12500,
  averageRating: 4.5,
  memberSince: '2023-06-15',
  passengerId: 'passenger1',
};
